### PR TITLE
Add support for Go modules

### PR DESCRIPTION
**Pull request by tklauser**
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

### CODE REVIEW

**Comment by vishvananda** [comment]
This seems reasonable to me, but I'm not sure if this will affect anyone using this in older projects.

**Comment by tklauser** [comment]
This shouldn't affect anyone using it on older projects. They can still use it as before.

**Comment by tklauser** [comment]
Ping?

**Comment by aboch** [comment]
LGTM

**Pull request merged**
