### PR TITLE
Add support for arm64

### PR DESCRIPTION
**Pull request by dave-tucker**
This should fix the issues seen in docker/libnetwork#198

Signed-off-by: Dave Tucker <dt@docker.com>

### CODE REVIEW

**Comment by dave-tucker** [comment]
@vishvananda - please don't merge until @hqhq has tested. Thanks!

**Comment by vishvananda** [comment]
lgtm but waiting on @hqhq

**Comment by hqhq** [comment]
After applying your patch, I got:
```
# go test github.com/vishvananda/netlink/
# github.com/vishvananda/netns
github.com/vishvananda/netns/netns_linux_arm64.go:6:2: error: redefinition of ‘SYS_SETNS’
  SYS_SETNS = 375
  ^
github.com/vishvananda/netns/netns_linux_amd.go:4:2: note: previous definition of ‘SYS_SETNS’ was here
  SYS_SETNS = 308
  ^
FAIL    github.com/vishvananda/netlink [build failed]
```
So I added `+build linux,amd` to `netns_linux_amd.go`, but I still got the error before:
```
root@linaro-developer:/go/src/github.com/docker/docker/vendor/src# go test github.com/vishvananda/netlink/
--- FAIL: TestLinkAddDelDummy (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestLinkAddDelVlan (0.25s)
        testing.go:278: operation not supported
--- FAIL: TestLinkAddDelMacvlan (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestLinkAddDelBridgeMaster (0.51s)
        testing.go:278: operation not supported
--- FAIL: TestLinkSetUnsetResetMaster (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestLinkSetNs (0.24s)
        testing.go:278: Failed to set basens
--- FAIL: TestLinkAddDelVxlan (0.55s)
        testing.go:278: operation not supported
--- FAIL: TestLinkAddDelIPVlanL2 (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestLinkAddDelIPVlanL3 (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestLinkByIndex (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestLinkSet (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestNeighAddDel (0.00s)
        testing.go:278: operation not supported
--- FAIL: TestProtinfo (0.03s)
        testing.go:278: operation not supported
--- FAIL: TestXfrmPolicyAddDel (0.00s)
        testing.go:278: protocol not supported
--- FAIL: TestXfrmStateAddDel (0.24s)
        testing.go:278: protocol not supported
FAIL
FAIL    github.com/vishvananda/netlink  4.107s
```

**Comment by dave-tucker** [comment]
Hmmm, let me see if I can replicate in QEMU

**Comment by tianon** [comment]
That `amd` should be `amd64`, shouldn't it?

**Comment by tianon** [comment]
(hoping that's just a typo in the comment)

**Comment by hqhq** [comment]
@tianon It's not a typo, but it's already been fixed :)

**Comment by vishvananda** [comment]
@dave-tucker any word on this?

**Comment by hqhq** [comment]
Maybe we can merge this patch first, because we definitely need it, without this, we can't even compile Docker on ARM64 now.

And I confirmed I got the same error as I posted in https://github.com/docker/libnetwork/issues/198 on the latest code with this patch applied, we can keep tracking this in that issue.

Thanks for your help.

**Comment by dave-tucker** [comment]
Closed in favour of #6

**Pull request closed without merging**
