### PR TITLE
Enable errcheck, errorlint, gci and gofumpt linters

### PR DESCRIPTION
**Pull request by mmorel-35**
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

### CODE REVIEW

**Comment by jeffwidman** [comment]
Curious what prompted this and also why you closed it?

**Comment by mmorel-35** [comment]
Just wanted to add more linters
But gofumpt is failing on windows I have no clue why 😅

**Comment by jeffwidman** [comment]
Weird. And 👍 in general for more linters if you choose to add them. I personally like `goimports`, not sure if that's included indirectly in this list...

**Comment by mmorel-35** [comment]
Hi @jeffwidman ,
I have opened #71 instead, goimports and gci are doing thesame job. From what I can see on other projects gci is frequently used because of its flexibility

**Pull request closed without merging**
