### PR TITLE
Get netns building on windows

### PR DESCRIPTION
**Pull request by madhanrm**
Just move around the code to get it building on windows

### CODE REVIEW

**Comment by madhanrm** [comment]
Fix for https://github.com/vishvananda/netns/issues/23

**Comment by olljanat** [comment]
@madhanrm was there some reason why you closed this one?

**Comment by madhanrm** [comment]
I didn't need this at that point, so closed this one.

**Comment by olljanat** [comment]
Ok. Thanks for quick answer. I will try if that fixes my issue and create new PR based on this.

**Pull request closed without merging**
